### ISSUE TITLE
Event to monitor changes to global variables

### ISSUE THREAD

**Issue by Petethegoat** [MWSE/MWSE#130]
Something like `event.register("globalVarChanged", onNewDay, {filter = "Day"}` or `event.register("globalVarChanged", onSlaveFreed", {filter = "FreedSlavesCounter"})`

Probably should have:
- the global variable
- the previous value of the global variable
- the current value of the global variable

**Comment by NullCascade** [comment]
This one is unlikely to be tackled in a timely manner. The way that global variables are modified isn't through a setGlobal/modGlobal command. Instead they're cached on a few different objects, and the values are modified directly. This means there would have to be several specific assembly injections instead of just overwriting the (non-existant) setGlobal function call to point to a MWSE function.

Not saying no, but this isn't going to happen immediately.
