### ISSUE TITLE
game crashes when you try to get text from dialog info

### ISSUE THREAD

**Issue by qqqbbb** [MWSE/MWSE#209]
```
local function OnInfoGetText(eventData)
	mwse.log('OnInfoGetText %s', type(eventData.info.text));
end
event.register('infoGetText', OnInfoGetText);
```

**Comment by Elanhant** [comment]
Necroposting, but in case someone stumbles upon this — in newer version of MWSE `loadOriginalText` should be used to get the text from dialogue info (https://mwse.readthedocs.io/en/latest/lua/event/infoGetText.html).

I presume that accessing `info.text` directly leads to an infinite loop, since the event is emitted when the text is being accessed.
