### ISSUE TITLE
Pinnable menu blocks

### ISSUE THREAD

**Issue by jhaakma** [MWSE/MWSE#88]
Vanilla Menu blocks have a box you can click to pin it to the screen after the menu is closed. Is there a way to hook into that functionality for custom UI elements?

**Comment by Hrnchamd** [comment]
Custom menus are pinned to the screen by default. All of the world interaction menus call menu:destroy() to remove the menu after you finish, rather than being cleaned up by the engine.

To have a menu hide itself when out of menumode use ``menu:setPropertyBool("menu_is_docked", true)``.

If you want a pinning toggle box, that requires more research.
